2021-05-19T11:29:48+0200 [main] t3.utils.ab.h.y()
WARNING: Missing file to load: properties.dat. Skipping this step.
2021-05-19T11:29:48+0200 [main] t3.utils.ab.h.y()
WARNING: Missing file to load: properties.dat. Skipping this step.
2021-05-19T11:29:48+0200 [main] t3.utils.ab.r.aXm()
WARNING: Cannot read managed property store from disk: java.lang.NullPointerException
	at java.base/java.io.ByteArrayInputStream.<init>(Unknown Source)
	at t3.utils.ab.r.aXm(ManagedPropertyStore.java:228)
	at t3.utils.ab.ab.aXp(PropertyStore.java:248)
	at t3.utils.ab.ab.get(PropertyStore.java:245)
	at t3.utils.ab.x.a(PropertyStore.java:64)
	at t3.utils.ab.w.a(PropertyStore.java:245)
	at t3.utils.ab.r.aXl(ManagedPropertyStore.java:224)
	at t3.utils.ab.r.a(ManagedPropertyStore.java:128)
	at t3.utils.ab.r.rC(ManagedPropertyStore.java:87)
	at t3.common.lic.a.i.bw(UsageTokenStore.java:30)
	at t3.common.lic.a.b.aT(AccountBasedLicenseManager.java:30)
	at t3.common.lic.k.<init>(LicenseManager.java:50)
	at t3.common.lic.k.<init>(LicenseManager.java:37)
	at t3.utils.a.au(App.java:347)
	at t3.dataman.mongodb.app.Studio3TApp.main(Studio3TApp.java:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
2021-05-19T11:29:48+0200 [main] t3.utils.ab.r.aXm()
WARNING: Cannot read managed property store from disk: java.lang.NullPointerException
	at java.base/java.io.ByteArrayInputStream.<init>(Unknown Source)
	at t3.utils.ab.r.aXm(ManagedPropertyStore.java:228)
	at t3.utils.ab.ab.aXp(PropertyStore.java:248)
	at t3.utils.ab.ab.get(PropertyStore.java:245)
	at t3.utils.ab.x.a(PropertyStore.java:64)
	at t3.utils.ab.w.a(PropertyStore.java:245)
	at t3.utils.ab.r.aXl(ManagedPropertyStore.java:224)
	at t3.utils.ab.r.a(ManagedPropertyStore.java:128)
	at t3.utils.ab.r.rC(ManagedPropertyStore.java:87)
	at t3.common.lic.d.b.ck(InstanceIdStore.java:27)
	at t3.common.lic.d.c.<init>(LicServerApiClient.java:41)
	at t3.common.lic.a.b.aT(AccountBasedLicenseManager.java:30)
	at t3.common.lic.k.<init>(LicenseManager.java:50)
	at t3.common.lic.k.<init>(LicenseManager.java:37)
	at t3.utils.a.au(App.java:347)
	at t3.dataman.mongodb.app.Studio3TApp.main(Studio3TApp.java:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
2021-05-19T11:29:48+0200 [main] t3.utils.ab.r.aXm()
WARNING: Cannot read managed property store from disk: java.lang.NullPointerException
	at java.base/java.io.ByteArrayInputStream.<init>(Unknown Source)
	at t3.utils.ab.r.aXm(ManagedPropertyStore.java:228)
	at t3.utils.ab.ab.aXp(PropertyStore.java:248)
	at t3.utils.ab.ab.get(PropertyStore.java:245)
	at t3.utils.ab.x.a(PropertyStore.java:64)
	at t3.utils.ab.w.a(PropertyStore.java:245)
	at t3.utils.ab.r.aXl(ManagedPropertyStore.java:224)
	at t3.utils.ab.r.a(ManagedPropertyStore.java:128)
	at t3.utils.ab.r.rC(ManagedPropertyStore.java:87)
	at t3.common.b.i.i(T3AccountStore.java:22)
	at t3.common.b.h.<init>(T3AccountManager.java:25)
	at t3.common.lic.d.c.<init>(LicServerApiClient.java:42)
	at t3.common.lic.a.b.aT(AccountBasedLicenseManager.java:30)
	at t3.common.lic.k.<init>(LicenseManager.java:50)
	at t3.common.lic.k.<init>(LicenseManager.java:37)
	at t3.utils.a.au(App.java:347)
	at t3.dataman.mongodb.app.Studio3TApp.main(Studio3TApp.java:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
2021-05-19T11:30:14+0200 [main] t3.utils.connman.gg.a()
WARNING: No Robo3TConfiguration is found. Skipping this step
2021-05-19T11:30:15+0200 [main] t3.common.lic.a.b.b()
WARNING: Failed to install license: t3.common.lic.d.d: Not logged in.
	at t3.common.b.h.a(T3AccountManager.java:103)
	at t3.common.lic.d.c.c(LicServerApiClient.java:113)
	at t3.common.lic.a.b.b(AccountBasedLicenseManager.java:135)
	at t3.dataman.mongodb.app.Studio3TApp.JR(Studio3TApp.java:192)
	at t3.dataman.mongodb.app.Studio3TApp.main(Studio3TApp.java:86)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
2021-05-19T11:30:16+0200 [main] t3.utils.ai.o.bdS()
WARNING: e {} was not saved
2021-05-19T11:30:16+0200 [main] t3.utils.ab.r.aXm()
WARNING: Cannot read managed property store from disk: java.lang.NullPointerException
	at java.base/java.io.ByteArrayInputStream.<init>(Unknown Source)
	at t3.utils.ab.r.aXm(ManagedPropertyStore.java:228)
	at t3.utils.ab.ab.aXp(PropertyStore.java:248)
	at t3.utils.ab.ab.get(PropertyStore.java:245)
	at t3.utils.ab.x.a(PropertyStore.java:64)
	at t3.utils.ab.w.a(PropertyStore.java:245)
	at t3.utils.ab.r.aXl(ManagedPropertyStore.java:224)
	at t3.utils.ab.r.a(ManagedPropertyStore.java:128)
	at t3.utils.ab.r.rC(ManagedPropertyStore.java:87)
	at t3.utils.ab.l.<clinit>(DefaultTrustedPropertyStore.java:16)
	at t3.utils.connman.fk.ct(MongoConnectionInfoRestrictions.java:76)
	at t3.utils.connman.fk.ahq(MongoConnectionInfoRestrictions.java:147)
	at t3.utils.connman.fk.<init>(MongoConnectionInfoRestrictions.java:43)
	at t3.utils.connman.cd.<init>(ConnectionManager.java:103)
	at t3.utils.connman.cd.aeV(ConnectionManager.java:111)
	at t3.dataman.mongodb.app.a.<init>(AppController.java:135)
	at t3.dataman.mongodb.app.ad.run(AppRunner.java:154)
	at t3.dataman.mongodb.app.Studio3TApp.main(Studio3TApp.java:92)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
2021-05-19T11:30:16+0200 [main] t3.utils.ai.o.bdS()
WARNING: e {} was not saved
2021-05-19T11:30:16+0200 [main] t3.utils.ai.o.bdS()
WARNING: e {} was not saved
2021-05-19T11:30:17+0200 [main] t3.utils.ai.o.bdS()
WARNING: e {} was not saved
2021-05-19T11:31:41+0200 [cluster-ClusterId{value='60a4dafdfd5b7c5838c42998', description='null'}-cluster0-shard-00-00.pvve8.mongodb.net:27017] t3.utils.connman.d.b.connect()
WARNING: there should be no SSL calls prior to TCP connect
2021-05-19T11:31:41+0200 [cluster-ClusterId{value='60a4dafdfd5b7c5838c42998', description='null'}-cluster0-shard-00-02.pvve8.mongodb.net:27017] t3.utils.connman.d.b.connect()
WARNING: there should be no SSL calls prior to TCP connect
2021-05-19T11:31:41+0200 [cluster-ClusterId{value='60a4dafdfd5b7c5838c42998', description='null'}-cluster0-shard-00-01.pvve8.mongodb.net:27017] t3.utils.connman.d.b.connect()
WARNING: there should be no SSL calls prior to TCP connect
2021-05-19T11:31:41+0200 [3T::Connection Manager Thread] t3.utils.connman.d.b.connect()
WARNING: there should be no SSL calls prior to TCP connect
2021-05-19T11:31:41+0200 [main] t3.utils.connman.fw.a()
ERROR: Update is ProgressUpdate: Connecting to server Database error (MongoSecurityException): Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='admin', source='admin', password=<hidden>, mechanismProperties=<hidden>}

Stacktrace:
|_/ Database error (MongoSecurityException): Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='admin', source='admin', password=<hidden>, mechanismProperties=<hidden>}
|____/ Mongo Server error (MongoCommandException): Command failed with error 8000 (AtlasError): 'bad auth : Authentication failed.' on server cluster0-shard-00-02.pvve8.mongodb.net:27017. 
|____... 
|____... The full response is:
|____... { 
|____...     "ok" : 0.0, 
|____...     "errmsg" : "bad auth : Authentication failed.", 
|____...     "code" : 8000.0, 
|____...     "codeName" : "AtlasError"
|____... }: t3.utils.connman.cl: Database error (MongoSecurityException): Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='admin', source='admin', password=<hidden>, mechanismProperties=<hidden>}

Stacktrace:
|_/ Database error (MongoSecurityException): Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='admin', source='admin', password=<hidden>, mechanismProperties=<hidden>}
|____/ Mongo Server error (MongoCommandException): Command failed with error 8000 (AtlasError): 'bad auth : Authentication failed.' on server cluster0-shard-00-02.pvve8.mongodb.net:27017. 
|____... 
|____... The full response is:
|____... { 
|____...     "ok" : 0.0, 
|____...     "errmsg" : "bad auth : Authentication failed.", 
|____...     "code" : 8000.0, 
|____...     "codeName" : "AtlasError"
|____... }
	at t3.utils.connman.d.d.b(MongoDBConnector.java:520)
	at t3.utils.connman.d.d.c(MongoDBConnector.java:1039)
	at t3.utils.connman.cd.d(ConnectionManager.java:1288)
	at t3.utils.connman.cd.c(ConnectionManager.java:1218)
	at t3.utils.connman.cd.f(ConnectionManager.java:418)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='admin', source='admin', password=<hidden>, mechanismProperties=<hidden>}
	at com.mongodb.internal.connection.SaslAuthenticator.wrapException(SaslAuthenticator.java:201)
	at com.mongodb.internal.connection.SaslAuthenticator.access$300(SaslAuthenticator.java:40)
	at com.mongodb.internal.connection.SaslAuthenticator$1.run(SaslAuthenticator.java:78)
	at com.mongodb.internal.connection.SaslAuthenticator$1.run(SaslAuthenticator.java:47)
	at com.mongodb.internal.connection.SaslAuthenticator.doAsSubject(SaslAuthenticator.java:207)
	at com.mongodb.internal.connection.SaslAuthenticator.authenticate(SaslAuthenticator.java:47)
	at com.mongodb.internal.connection.InternalStreamConnectionInitializer.authenticateAll(InternalStreamConnectionInitializer.java:156)
	at com.mongodb.internal.connection.InternalStreamConnectionInitializer.initialize(InternalStreamConnectionInitializer.java:63)
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:129)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.open(UsageTrackingInternalConnection.java:50)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.open(DefaultConnectionPool.java:398)
	at com.mongodb.internal.connection.DefaultConnectionPool.get(DefaultConnectionPool.java:115)
	at com.mongodb.internal.connection.DefaultConnectionPool.get(DefaultConnectionPool.java:101)
	at com.mongodb.internal.connection.DefaultServer.getConnection(DefaultServer.java:92)
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.getConnection(ClusterBinding.java:133)
	at com.mongodb.client.internal.ClientSessionBinding$SessionBindingConnectionSource.getConnection(ClientSessionBinding.java:135)
	at com.mongodb.operation.CommandOperationHelper$5.call(CommandOperationHelper.java:207)
	at com.mongodb.operation.OperationHelper.withReadConnectionSource(OperationHelper.java:463)
	at com.mongodb.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:203)
	at com.mongodb.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:198)
	at com.mongodb.operation.CommandReadOperation.execute(CommandReadOperation.java:59)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:194)
	at com.mongodb.client.internal.MongoDatabaseImpl.executeCommand(MongoDatabaseImpl.java:194)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:163)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:158)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:148)
	at t3.utils.connman.d.d.a(MongoDBConnector.java:759)
	at t3.utils.connman.d.d.b(MongoDBConnector.java:393)
	at t3.utils.connman.d.d.c(MongoDBConnector.java:1039)
	...
2021-05-19T11:31:41+0200 [3T::Connection Manager Thread] t3.utils.connman.d.b.connect()
WARNING: there should be no SSL calls prior to TCP connect
2021-05-19T11:32:19+0200 [cluster-ClusterId{value='60a4db23fd5b7c5838c4299b', description='null'}-cluster0-shard-00-02.pvve8.mongodb.net:27017] t3.utils.connman.d.b.connect()
WARNING: there should be no SSL calls prior to TCP connect
2021-05-19T11:32:19+0200 [cluster-ClusterId{value='60a4db23fd5b7c5838c4299b', description='null'}-cluster0-shard-00-00.pvve8.mongodb.net:27017] t3.utils.connman.d.b.connect()
WARNING: there should be no SSL calls prior to TCP connect
2021-05-19T11:32:19+0200 [cluster-ClusterId{value='60a4db23fd5b7c5838c4299b', description='null'}-cluster0-shard-00-01.pvve8.mongodb.net:27017] t3.utils.connman.d.b.connect()
WARNING: there should be no SSL calls prior to TCP connect
2021-05-19T11:32:19+0200 [3T::Connection Manager Thread] t3.utils.connman.d.b.connect()
WARNING: there should be no SSL calls prior to TCP connect
2021-05-19T11:32:20+0200 [3T::Connection Manager Thread] t3.utils.connman.h.b()
WARNING: consider using isEffectiveVersionOrLater for comparing version against 3.4 or above
2021-05-19T11:32:32+0200 [3T::server command] t3.utils.connman.d.b.connect()
WARNING: there should be no SSL calls prior to TCP connect
